server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://39.168.187.30:3306/apidoc?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: shiji159
